

const ActionTypes = {
    SIGNIN_SUCCESS : "SIGNIN_SUCCESS",
    SIGNIN_FAILED : "SIGNIN_FAILED",
    SIGNUP_SUCCESS : "SIGNUP_SUCCESS",
    SIGNUP_FAILED : "SIGNUP_FAILED",
    LOGGED_OUT : "LOGGED_OUT",
    GET_PATIENTS : "GET_PATIENTS",
    ADD_PATIENT : "ADD_PATIENT",
    GET_HISTORY : "GET_HISTORY",
    ADD_RECORD : "ADD_RECORD",
    ID : "ID"
}
export default ActionTypes